@extends('admin.layout.app')

@push('styles')
    <style>
        .dataTables_filter {
            float:right;
        }
        #example1_paginate {
            float: right;
        }
        .text-center-row>th,
        .text-center-row>td {
            text-align: center;
            vertical-align: top;
        }
    </style>
@endpush

@section('content')
    <div class="main-content">
        <h2 class="mb-5 pb-3" style="border-bottom:1px solid #efefef;">SUMMARY WORK REPORT</h2>

        <table id="example1" class="table table-striped text-center align-middle" style="width:100%">
            <thead>
            <tr>
                <th colspan="13" >Felling/ Chipping</th>
                <th colspan="12">Debolling</th>
            </tr>
            <tr>
                <th>SAHDAN-LYK226</th>
                <th>NAIM-LYK243</th>
                <th>SALMAN-LYK244</th>
                <th>KARIM/LYK244</th>
                <th>ASWAN/LYK228</th>
                <th>KADIR/LYK245</th>
                <th>RUSTAM/LYK244</th>
                <th>SAMSUDIN/LYK208</th>
                <th>0</th>
                <th>0</th>
                <th>0</th>
                <th>Total (Palms)</th>
                <th></th>
                <th></th>
                <th>Remark</th>
                <th>SAHDAN-LYK226</th>
                <th>NAIM-LYK243</th>
                <th>SALMAN-LYK244</th>
                <th>KARIM/LYK244</th>
                <th>ASWAN/LYK228</th>
                <th>KADIR/LYK245</th>
                <th>RUSTAM/LYK244</th>
                <th>SAMSUDIN/LYK208</th>
                <th>Total (Palms)</th>
                <th></th>
                <th></th>
                <th>Remark</th>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>Today</th>
                <th>MTodate</th>
                <th>YID</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>Today</th>
                <th>MTodate</th>
                <th>YID</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th>CUTI</th>
                <td></td>
                <td>CUTI</td>
                <td>CUTI</td>
                <td>ROSAK</td>
                <td>ROSAK</td>
                <td></td>
                <td>CUTI</td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>48245</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>CECT</td>
                <td>260</td>
                <td>ROSAK</td>
                <td>ROSAK</td>
                <td></td>
                <td>CECT</td>
                <td></td>
                <td></td>
                <td></td>
                <td>260</td>
                <td>260</td>
                <td>48505</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>CECT</td>
                <td>240</td>
                <td>ROSAK</td>
                <td>ROSAK</td>
                <td></td>
                <td>CECT</td>
                <td></td>
                <td></td>
                <td></td>
                <td>240</td>
                <td>500</td>
                <td>48745</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>CECT</td>
                <td>264</td>
                <td>ROSAK</td>
                <td>ROSAK</td>
                <td></td>
                <td>CECT</td>
                <td></td>
                <td></td>
                <td></td>
                <td>264</td>
                <td>764</td>
                <td>49009</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>CECT</td>
                <td>270</td>
                <td>NFD</td>
                <td>ROSAK</td>
                <td></td>
                <td>BOOR HDS</td>
                <td></td>
                <td></td>
                <td></td>
                <td>270</td>
                <td>1034</td>
                <td>49279</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>CECT</td>
                <td>270</td>
                <td>ROSAK</td>
                <td>ROSAK</td>
                <td></td>
                <td>CECT</td>
                <td></td>
                <td></td>
                <td></td>
                <td>270</td>
                <td>1304</td>
                <td>49279</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>CECT</td>
                <td>250</td>
                <td>ROSAK</td>
                <td>ROSAK</td>
                <td></td>
                <td>CECT</td>
                <td></td>
                <td></td>
                <td></td>
                <td>250</td>
                <td>1554</td>
                <td>49549</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>CECT</td>
                <td>215</td>
                <td>ROSAK</td>
                <td>ROSAK</td>
                <td></td>
                <td>CECT</td>
                <td></td>
                <td></td>
                <td></td>
                <td>215</td>
                <td>1769</td>
                <td>49799</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>TIDAK KERJA</td>
                <td>GNTI SPOKET</td>
                <td>ROSAK</td>
                <td>ROSAK</td>
                <td></td>
                <td>CECT</td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>1769</td>
                <td>50014</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>BT PRT TGH</td>
                <td>230</td>
                <td>NFD</td>
                <td>ROSAK</td>
                <td></td>
                <td>BT PRT TGH</td>
                <td></td>
                <td></td>
                <td></td>
                <td>230</td>
                <td>1999</td>
                <td>50014</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>BT PRT TGH</td>
                <td>CUTI</td>
                <td>BT PRT TLG</td>
                <td>NFD</td>
                <td></td>
                <td>BT PRT TGH</td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>1999</td>
                <td>50244</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>110</td>
                <td>114</td>
                <td>BT PRT TLG</td>
                <td>ROSAK</td>
                <td></td>
                <td>BT PRT TGH</td>
                <td></td>
                <td></td>
                <td></td>
                <td>224</td>
                <td>2223</td>
                <td>50244</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0</td>
                <td>50932</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>194</td>
                <td>234</td>
                <td>BT PRT TLG</td>
                <td>ROSAK</td>
                <td></td>
                <td>160</td>
                <td></td>
                <td></td>
                <td></td>
                <td>588</td>
                <td>2811</td>
                <td>50468</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>264</td>
                <td>264</td>
                <td>51196</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>HOLLING</td>
                <td>290</td>
                <td>BT PRT TLG</td>
                <td>ROSAK</td>
                <td></td>
                <td>180</td>
                <td></td>
                <td></td>
                <td></td>
                <td>470</td>
                <td>3281</td>
                <td>51056</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>182</td>
                <td>677</td>
                <td>941</td>
                <td>51873</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>HOLLING</td>
                <td>280</td>
                <td>BT PRT TLG</td>
                <td>ROSAK</td>
                <td></td>
                <td>200</td>
                <td></td>
                <td></td>
                <td></td>
                <td>480</td>
                <td>3761</td>
                <td>51526</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>198</td>
                <td>528</td>
                <td>1469</td>
                <td>52401</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>CECT</td>
                <td>290</td>
                <td>BT PRT TLG</td>
                <td>ROSAK</td>
                <td></td>
                <td>200</td>
                <td></td>
                <td></td>
                <td></td>
                <td>490</td>
                <td>4251</td>
                <td>52006</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>231</td>
                <td>567</td>
                <td>2026</td>
                <td>52958</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>CECT</td>
                <td>260</td>
                <td>BT PRT TLG</td>
                <td>ROSAK</td>
                <td></td>
                <td>190</td>
                <td></td>
                <td></td>
                <td></td>
                <td>450</td>
                <td>4701</td>
                <td>52496</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>231</td>
                <td>561</td>
                <td>2587</td>
                <td>53519</td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>231</td>
                <td>528</td>
                <td>3115</td>
                <td>54047</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>CECT</td>
                <td>200</td>
                <td>BT PRT TLG</td>
                <td>ROSAK</td>
                <td></td>
                <td>150</td>
                <td></td>
                <td></td>
                <td></td>
                <td>350</td>
                <td>5051</td>
                <td>52946</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>165</td>
                <td>375</td>
                <td>3490</td>
                <td>54422</td>
                <td></td>
            </tr>
            <tr>
                <th>CUTI</th>
                <td></td>
                <td>CUTI</td>
                <td>CUTI</td>
                <td>CUTI</td>
                <td>ROSAK</td>
                <td></td>
                <td>CUTI</td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>5051</td>
                <td>53296</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>3490</td>
                <td>54422</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>CECT</td>
                <td>200</td>
                <td>BT PRT TLG</td>
                <td>ROSAK</td>
                <td></td>
                <td>120</td>
                <td></td>
                <td></td>
                <td></td>
                <td>320</td>
                <td>5371</td>
                <td>53616</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>138</td>
                <td>358</td>
                <td>3848</td>
                <td>54780</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>CUTI</td>
                <td>239</td>
                <td>163</td>
                <td>ROSAK</td>
                <td></td>
                <td>130</td>
                <td></td>
                <td></td>
                <td></td>
                <td>532</td>
                <td>5903</td>
                <td>54148</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>220</td>
                <td></td>
                <td></td>
                <td></td>
                <td>142</td>
                <td>599</td>
                <td>4447</td>
                <td>55379</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>CECT</td>
                <td>244</td>
                <td>285</td>
                <td>ROSAK</td>
                <td></td>
                <td>300</td>
                <td></td>
                <td></td>
                <td></td>
                <td>829</td>
                <td>6732</td>
                <td>54977</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>264</td>
                <td>193</td>
                <td></td>
                <td></td>
                <td>330</td>
                <td>926</td>
                <td>5373</td>
                <td>56305</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>CECT</td>
                <td>300</td>
                <td>290</td>
                <td>ROSAK</td>
                <td></td>
                <td>240</td>
                <td></td>
                <td></td>
                <td></td>
                <td>830</td>
                <td>7562</td>
                <td>55807</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>266</td>
                <td>330</td>
                <td></td>
                <td></td>
                <td>264</td>
                <td>924</td>
                <td>6297</td>
                <td>57229</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>CECT</td>
                <td>239</td>
                <td>262</td>
                <td>ROSAK</td>
                <td></td>
                <td>270</td>
                <td></td>
                <td></td>
                <td></td>
                <td>771</td>
                <td>8333</td>
                <td>56578</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>330</td>
                <td>330</td>
                <td></td>
                <td></td>
                <td>297</td>
                <td>858</td>
                <td>7155</td>
                <td>58087</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td>CECT</td>
                <td>244</td>
                <td>282</td>
                <td>ROSAK</td>
                <td></td>
                <td>200</td>
                <td></td>
                <td></td>
                <td></td>
                <td>726</td>
                <td>9059</td>
                <td>57304</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>264</td>
                <td>297</td>
                <td></td>
                <td></td>
                <td>231</td>
                <td>827</td>
                <td>7982</td>
                <td>58914</td>
                <td></td>
            </tr>
            <tr>
                <th>HOLUNG</th>
                <td></td>
                <td>CECT</td>
                <td>300</td>
                <td>257</td>
                <td>ROSAK</td>
                <td></td>
                <td>217</td>
                <td></td>
                <td></td>
                <td></td>
                <td>774</td>
                <td>9833</td>
                <td>58078</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>266</td>
                <td>330</td>
                <td></td>
                <td></td>
                <td>247</td>
                <td>874</td>
                <td>8356</td>
                <td>59783</td>
                <td></td>
            </tr>
            <tr>
                <th>HOLUNG</th>
                <td></td>
                <td>CECT</td>
                <td>240</td>
                <td>226</td>
                <td>ROSAK</td>
                <td></td>
                <td>117</td>
                <td></td>
                <td></td>
                <td></td>
                <td>583</td>
                <td>10416</td>
                <td>58661</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>330</td>
                <td>297</td>
                <td></td>
                <td></td>
                <td>132</td>
                <td>660</td>
                <td>9516</td>
                <td>60448</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>CECT</td>
                <td>150</td>
                <td>267</td>
                <td>ROSAK</td>
                <td></td>
                <td>267</td>
                <td></td>
                <td></td>
                <td></td>
                <td>684</td>
                <td>11100</td>
                <td>59345</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>264</td>
                <td>264</td>
                <td></td>
                <td></td>
                <td>297</td>
                <td>792</td>
                <td>10308</td>
                <td>61240</td>
                <td></td>
            </tr>
            <tr>
                <th>CECT</th>
                <td></td>
                <td>CECT</td>
                <td>240</td>
                <td>263</td>
                <td>ROSAK</td>
                <td></td>
                <td>150</td>
                <td></td>
                <td></td>
                <td></td>
                <td>653</td>
                <td>11753</td>
                <td>59998</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>165</td>
                <td>330</td>
                <td></td>
                <td></td>
                <td>165</td>
                <td>726</td>
                <td>11034</td>
                <td>61966</td>
                <td></td>
            </tr>
            <tr>
                <th>STACKING</th>
                <td></td>
                <td></td>
                <td></td>
                <td>293</td>
                <td>ROSAK</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>293</td>
                <td>12046</td>
                <td>60291</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>264</td>
                <td>297</td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>11034</td>
                <td>61966</td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>ROSAK</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>12046</td>
                <td>60291</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>11034</td>
                <td>61966</td>
                <td></td>
            </tr>
            </tbody>
        </table>
    </div>
@endsection

@push('scripts')
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <script>
        new DataTable('#example1');
    </script>
@endpush
