@extends('admin.layout.app')

@push('styles')
    <style>
        .dataTables_filter {
            float:right;
        }
        #example2_paginate {
            float: right;
        }
        #example3_paginate {
            float: right;
        }
        #example4_paginate {
            float: right;
        }
        .table thead th{
            border: 1px solid;
            text-align: center;
        }
        .table thead tp{
            border: 1px solid;
            text-align: left;
        }
    </style>
@endpush

@section('content')
    <div class="main-content">
        <h2 class="mb-5 pb-3" style="font-weight:bold;border-bottom:1px solid #efefef;">WORK DONE For Claim</h2>
        <div style="border: 1px solid; width: 300px; padding-top: 10px; margin-top: -40px;">
            <p style="border-bottom: 1px solid">Month: 10 / 2023</p>
            <p style="border-bottom: 1px solid">Block: 2023 A/B</p>
            <p style="border-bottom: 1px solid">Client: Sime Darby </p>
            <p style="border-bottom: 1px solid">Estate: Takau Estate</p>
            <p style="border-bottom: 1px solid">Surveyor: Janter</p>
            <p>Contractor: LYK Hong & Sons Realty Sdn. Bhd.</p>
        </div>
        <br>
        <table id="example2" class="table table-striped" style="width:100%">
            <thead>
            <tr>
                <th>No</th>
                <th>Description of Work</th>
                <th>UOM</th>
                <th>Block</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>REMARK</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>Verified Qty</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>1</td>
                <td>New Field Drain</td>
                <td>m</td>
                <td>2023B</td>
                <td>1371.94</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>Edi </td>
                <td></td>
                <td></td>
                <td>589.98</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>Damak</td>
                <td></td>
                <td></td>
                <td>366.41</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>Naim</td>
                <td></td>
                <td></td>
                <td>47.11</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>Dahardi</td>
                <td></td>
                <td></td>
                <td>368.44</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>2</td>
                <td>New Collection Drain</td>
                <td>m</td>
                <td>2023B</td>
                <td>1607.84</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>Edi </td>
                <td></td>
                <td></td>
                <td>607.31</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>Damak</td>
                <td></td>
                <td></td>
                <td>925.28</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>Naim</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>Dahardi</td>
                <td></td>
                <td></td>
                <td>75.25</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>3</td>
                <td>Desilting Collection Drain</td>
                <td>m</td>
                <td>2023B</td>
                <td></td>
                <td></td>
                <td></td>
                <td>211.55</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>Total</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>211.55</td>
                <td>0</td>
                <td>211.55</td>
                <td></td>
            </tr>
            <tr>
                <td>4</td>
                <td>New Road</td>
                <td>m</td>
                <td>2023B</td>
                <td>124.4</td>
                <td>4500.22</td>
                <td></td>
                <td></td>
                <td>794.59</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>Total</td>
                <td>124.4</td>
                <td>4500.22</td>
                <td>0</td>
                <td>0</td>
                <td>794.59</td>
                <td>5419.21</td>
                <td></td>
            </tr>
            <tr>
                <td>5</td>
                <td>Compaction</td>
                <td>ha</td>
                <td>2023B</td>
                <td>0.45</td>
                <td></td>
                <td>2.46</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>2023A</td>
                <td>2.6</td>
                <td>4.82</td>
                <td>6.72</td>
                <td>5.57</td>
                <td>4.42</td>
                <td></td>
                <td>*Sept&#39; 23 WD</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>2023B</td>
                <td>9.22</td>
                <td></td>
                <td>7.33</td>
                <td>8.95</td>
                <td>12.03</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>Total</td>
                <td>12.27</td>
                <td>4.82</td>
                <td>16.51</td>
                <td>14.52</td>
                <td>16.45</td>
                <td>64.57</td>
                <td></td>
            </tr>
            <tr>
                <td>6</td>
                <td>Cambering</td>
                <td>ha</td>
                <td>2023B</td>
                <td>2.7</td>
                <td>1.83</td>
                <td>2.46</td>
                <td>1.55</td>
                <td>2.08</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>Total</td>
                <td>2.7</td>
                <td>1.83</td>
                <td>2.46</td>
                <td>1.55</td>
                <td>2.08</td>
                <td>10.62</td>
                <td></td>
            </tr>
            <tr>
                <td>7</td>
                <td>New Terraces</td>
                <td>m</td>
                <td>2023B</td>
                <td></td>
                <td></td>
                <td></td>
                <td>19760.23</td>
                <td></td>
                <td></td>
                <td>Galau: 15,626.03 m</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>(Paid in Sept&#39;23 Salary)</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>Total</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>19760.23</td>
                <td>0</td>
                <td>19760.23</td>
                <td></td>
            </tr>
            <tr>
                <td>8</td>
                <td>Hourly</td>
                <td>Hour</td>
                <td></td>
                <td>36</td>
                <td>83</td>
                <td>13</td>
                <td>46</td>
                <td>34</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>Total</td>
                <td>36</td>
                <td>83</td>
                <td>13</td>
                <td>46</td>
                <td>34</td>
                <td>212</td>
                <td></td>
            </tr>
            </tbody>
        </table>
        <br>
    </div>
@endsection

@push('scripts')
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <script>
        new DataTable('#example2');
    </script>
@endpush
